### ISSUE TITLE
Why not add localStorage to cache the scripts?

### ISSUE THREAD

**Issue by artknight** [getify/LABjs#120]
I think it would be fantastic to add the ability to cache the scripts via localStorage.

**Comment by jbmonroe** [comment]
IIRC, you can't load them back in from localStorage without using eval() to inject them into a page.  I think I'd have that filed under "Dubious Practices."

**Comment by getify** [comment]
There are other ways such as script injection. Thay said, I'm not really wild about doing our own caching. Browsers are better at it.

**Comment by jbmonroe** [comment]
I agree with that.  To some extent I'm not even sure caching is a good idea because I've already seen software break because non-cached transaction pages assumed that a new method would be available in a script and got nailed because the cached version of the script loaded.  I told the team to refactor in order to apply cache-breaking on the script loads.  (Unique environment, not running in a consumer browser.)

**Comment by artknight** [comment]
@getify the issue with browser caching is that sometimes the scripts are not getting cached very well and keep on getting reloaded every single time.

**Comment by getify** [comment]
That's awfully vague. If you can talk about specific details with caching, perhaps we can identify other causes (poor caching headers, etc). But I don't think we should fix our problem of a thumbtack by pulling out a sledgehammer. :)

**Comment by getify** [comment]
Any control you'd like to have over caching should be handled with service workers, IMO. I don't plan to build any caching behavior into the loader. It is possible eventually LABjs will ship a service worker for assistance, but that's far down the priority list, if ever.
